### ISSUE TITLE
Anzahl ausgegebener Publikationen pro Forschungsbereich 

### ISSUE THREAD

**Issue by BastianMelsheimer** [RRZE-Webteam/fau-cris#283]
Aktuell ist die Anzahl Publikationen, die in der Ansicht eines Forschungsbereichs ausgegeben wird, undokumentiert auf fünf beschränkt.

`[cris-custom show=fields field=232462209]
#publications#
[/cris-custom]`

Zeigt nur fünf, obwohl es zehn sind.

Interessanterweise gibt die Ergänzung eines "publications_orderby" die volle Liste.

`[cris-custom show=fields field=232462209 publications_orderby="year"]
#publications#
[/cris-custom]`

Lösung: Konfigurierbar machen und dokumentieren, was was macht.

**Comment by aajusah98** [comment]
Hi @BastianMelsheimer 
 I went through the above error,  As you have mentioned the `[cris-custom show=fields field=232462209] #publications# [/cris-custom]` code is giving only 5 publications, yes it's true it is giving 5 publications because the default value of the number of publications is 5.  and in case of other code there is attribute `'publications_orderby="year"` which will give all publication according to year. 

Question: what kind of configuration should we make there ? it's already configurable so that u can limit publications at the setting of plugin.

![research](https://user-images.githubusercontent.com/32913512/232558286-49623add-b028-4144-9725-4d104dd6d1a6.png)

**Comment by BastianMelsheimer** [comment]
Fixed in 3.22.4
